### ISSUE TITLE
Hide "RPC Server Ready" messagebox

### ISSUE THREAD

**Issue by justingrant** [hediet/vscode-rpc-server#1]
The "RPC Server Ready" messagebox shows up every time I launch VSCode or open a new VSCode window. and I have to manually dismiss it. This is annoying. 

Is this messagebox necessary?  Can it be hidden?

**Comment by hediet** [comment]
Sorry, I didn't see your issue until now. It is not necessary, I'll include a button "Show never again" in the next version.

**Comment by hediet** [comment]
Implemented in `v0.13.0`.
